apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    project: pagina_web
    environment: testing
spec:
  containers:
  - name: nginx
    image: nginx:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
